#this is context properties
#Tue May 05 13:48:45 CET 2026
Server=KALLALA
Database=DW_E-Commerce
Port=1433
User=sa
Password=enc\:routine.encryption.key.v1\:TfmZRCkw91/Y7HOllHom+lYgrppIFqMSeHqF49Ty8MNnIk+2jcU\=
Schema=
AddParms=
ServerName=KALLALA
AdditinalParms=
