#just for tac
statistics=true
job=Master_Job
jobVersion=0.1
date=2026-05-05 124855840
contextName=Default
jobId=_t-810BdhEfGcIM3ri9VIXw
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=PI_PA_MEHDI
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=